title: Shumpei Wakabayashi
description: A Robot Learns to Wash Dishes
profile_image: /assets/images/facephoto.JPG
wash_dish_image: /assets/images/wash_thumbnail.png
wash_dish_url: "https://shmpwk.github.io"
google_scholar_id: h4XYQ9EAAAAJ
github_username: shmpwk
linkedin_username: shumpei-wakabayashi
twitter_username: picckachu
youtube_username: \@shumpei.wakabayashi
instagram_username: shumpei.wakabayashi
email: wakabayashi@jsk.imi.i.u-tokyo.ac.jp
plugins:
  - jekyll-feed
header_pages:
  - about.md
  - publications.md
  - project.md
theme: minima
collections:
  projects:
    output: true
    permalink: /projects/:title/
